version: '3.9'
services:
  wireguard-server:
    container_name: wireguardServerDev
    environment:
      WG_HOST: ${HOST?Missing environment variable see readme}
      PASSWORD_HASH: ${ADMIN_PASSWORD:admin}
    ports:
      - 51821:51821/tcp
