version: '3.9'
services:
  wireguard-server:
    image: weejewel/wg-easy:7
    environment:
      WG_ALLOWED_IPS: 10.8.0.0/24
    volumes:
      - wireguardServerData:/etc/wireguard
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

volumes:
  wireguardServerData: